# 该配置文件请放入启动脚本 --spring.config.location 指定的目录下面
# 可参考 docker-build.sh 启动容器中的描述
spring:
  datasource:
    druid:
      url: jdbc:mysql://${MYSQL_IP:host.docker.internal}:3306/lx_doc?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false&zeroDateTimeBehavior=convertToNull
      username: root
      password: lx_doc_test
lx:
  doc:
    fileUpload:
      type: local # 文件上传类型，目前已实现local，minio，未实现 oss，接口 com.laxqnsys.core.sys.service.ISysFileUploadService
      path: /usr/attachment/${app.name} # 配置文件上传的地址
    docStorage:
      type: local # 文档存储类型，目前已实现的有 dataBase，local，minio，未实现 oss，接口：com.laxqnsys.core.doc.service.IDocFileContentStorageService
      path: ${lx.doc.fileUpload.path} # 文档内容存储的位置，如果类型是 dataBase ，此属性无效
log:
  home: /usr/logs/${app.name}
loglevel: INFO