# 该配置文件请放入启动脚本 --spring.config.location 指定的目录下面
# 可参考 docker-build.sh 启动容器中的描述
spring:
  datasource:
    druid:
      url: jdbc:mysql://host.docker.internal:3306/lx_doc?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false&zeroDateTimeBehavior=convertToNull
      username: root
      password: lx_doc_test
# 文件上传地址
lx:
  doc:
    fileUploadPath: /usr/attament/${app.name}
# 日志路径
log:
  home: /usr/logs/${app.name}
loglevel: INFO