# 该配置文件请放入启动脚本 --spring.config.location 指定的目录下面
# 可参考 docker-build.sh 启动容器中的描述
spring:
  datasource:
    druid:
      url: jdbc:mysql://${MYSQL_IP:host.docker.internal}:3306/lx_doc?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false&zeroDateTimeBehavior=convertToNull
      username: root
      password: lx_doc_test
lx:
  doc:
    fileUploadPath: /usr/attament/${app.name}
    storage:
      type: local # 采用本地磁盘存储，个人版提供 dataBase（文档内容数据库存储） 和 local（文档内容本次磁盘存储）
      path: /usr/${app.name}/doc/content
log:
  home: /usr/logs/${app.name}
loglevel: INFO