# 拉取基础镜像
FROM openjdk:8-jdk-alpine
# 维护人
MAINTAINER 951645267@qq.com

ENV SERVICE lx-doc

USER root

EXPOSE 9222
EXPOSE 80

# 安装 nginx
RUN apk add --no-cache nginx

# nginx 日志目录
RUN mkdir -p /var/log/nginx/
# web 静态资源存放目录，这个目录最好映射到宿主机
RUN mkdir -p /usr/web/html/
RUN mkdir -p /usr/nginx/config/
RUN mkdir -p /usr/app/${SERVICE}/
RUN mkdir -p /usr/logs/${SERVICE}/
RUN mkdir -p /usr/attament/${SERVICE}/

ADD run_in_docker_with_nginx.sh /usr/app/${SERVICE}/
COPY lx-core/target/lx-doc.jar /usr/app/${SERVICE}/

WORKDIR /usr/app/${SERVICE}/

ENTRYPOINT ["sh", "run_in_docker_with_nginx.sh", "start"]